routes/web.php
<?php

use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\CartController;
use App\Http\Controllers\Admin\VoucherController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\CreditNoteController;
use App\Http\Controllers\Admin\ReturnNoteController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\StoreController;
use App\Http\Controllers\Admin\ProviderController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\SaleQuoteController;
use App\Http\Controllers\Admin\FinancialCommitmentController;
use App\Http\Controllers\Admin\FundController;
use App\Http\Controllers\Admin\HistoryController;
use App\Http\Controllers\Admin\InventoryController;
use App\Http\Controllers\Admin\InvoiceController;
use App\Http\Controllers\Admin\MuController;
use App\Http\Controllers\Admin\OnlineSaleController;
use App\Http\Controllers\Admin\ProviderCommitmentController;
use App\Http\Controllers\Admin\ReturnCouponController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\SMSController;
use App\Http\Controllers\Shop\CouponController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => 'admin',
], function () {

    Route::get('/login', function () {
        return view('admin.auth.login');
    })->name('admin.login');

    Route::post('/login', [LoginController::class, 'login'])->name('admin.login');

    // Route::get('/forgot-password', function () {
    //     // $delete = DB::table('password_resets')->delete();
    //     return view('admin.auth.passwords.email');
    // })->middleware('guest')->name('admin.password.request');
    // Route::post('/forgot-password', [DealerResetPasswordController::class, 'forgot'])->middleware('guest')->name('admin.password.forgot');
    // Route::get('/reset-password/{token}', function ($token) {
    //     return view('admin.auth.passwords.reset', ['token' => $token]);
    // })->middleware('guest')->name('admin.password.reset');
    // Route::post('/reset-password', [DealerResetPasswordController::class, 'reset'])->middleware('guest')->name('admin.password.update');

    // Route::get('/register', function () {
    //     return view('admin.auth.register');
    // })->name('admin.register');
    // Route::post('/register', [DealerRegisterController::class, 'register'])->name('admin.register');

    Route::get('logout', [LoginController::class, 'logout']);
    Route::get('search', [ProductController::class, 'searchproduct'])->name('admin.product.searchproduct');
    Route::get('show', [ProductController::class, 'showproduct'])->name('admin.product.showproduct');

    Route::group([
        'middleware' => 'auth:web'
    ], function () {

        Route::get('/', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('admin.home');
        Route::get('/statistic/cart/total/{year}', [App\Http\Controllers\Admin\HomeController::class, 'cartTotalAmountByyearAndMonth'])->name('admin.cartTotalAmountByyearAndMonth');
        Route::get('/profile', [App\Http\Controllers\Admin\UserController::class, 'profile'])->name('admin.profile');
        Route::put('/profile/update', [App\Http\Controllers\Admin\UserController::class, 'updateProfile'])->name('admin.profile.update');

        //Product routes
        Route::group([
            'prefix' => 'product',
        ], function () {
            Route::get('/list', [ProductController::class, 'index'])->name('admin.product.index')->middleware(['can:Liste article']);
            Route::get('/getData', [ProductController::class, 'getData'])->name('admin.product.getData')->middleware(['can:Liste article']);
            Route::get('/create', [ProductController::class, 'create'])->name('admin.product.create')->middleware(['can:Ajouter article']);
            Route::post('/store', [ProductController::class, 'store'])->name('admin.product.store')->middleware(['can:Ajouter article']);
            Route::get('/{product}/edit', [ProductController::class, 'edit'])->name('admin.product.edit')->middleware(['can:Modifier article']);
            Route::put('/{product}/update', [ProductController::class, 'update'])->name('admin.product.update')->middleware(['can:Modifier article']);
            Route::get('/{product}/show', [ProductController::class, 'show'])->name('admin.product.show')->middleware(['can:Détails article']);
            Route::get('/{product}/delete', [ProductController::class, 'delete'])->name('admin.product.delete')->middleware(['can:Supprimer article']);
            Route::get('/{product}/settings', [ProductController::class, 'settings'])->name('admin.product.settings')->middleware(['can:Modifier les paramètres']);
            Route::put('/{product}/updatesettings', [ProductController::class, 'updateSettings'])->name('admin.product.updatesettings')->middleware(['can:Modifier les paramètres']);
            Route::get('/{product}/quantities', [ProductController::class, 'quantities'])->name('admin.product.quantities')->middleware(['can:Modifier les quantités']);
            Route::put('/{product}/updatequantities', [ProductController::class, 'updateQuantities'])->name('admin.product.updatequantities')->middleware(['can:Modifier les quantités']);
            Route::get('/{product}/barcodes', [ProductController::class, 'barcodes'])->name('admin.product.barcodes')->middleware(['can:Modifier les quantités']);
            Route::put('/{product}/updatebarcodes', [ProductController::class, 'updateBarcodes'])->name('admin.product.updatebarcodes')->middleware(['can:Modifier les quantités']);
            Route::get('/{product}/prices', [ProductController::class, 'prices'])->name('admin.product.prices')->middleware(['can:Modifier les prix']);
            Route::put('/{product}/updateprices', [ProductController::class, 'updatePrices'])->name('admin.product.updateprices')->middleware(['can:Modifier les prix']);
            Route::delete('/image/{image}', [ProductController::class, 'deleteImage'])->name('admin.product.deleteimage')->middleware(['can:Modifier article']);
            Route::put('/default/image/{image}', [ProductController::class, 'setDefaultImage'])->name('admin.product.setdefaultimage')->middleware(['can:Modifier article']);
            Route::get('/{product}/statistic/price/{from}/{to}', [App\Http\Controllers\Admin\ProductController::class, 'productPriceEvolution'])->name('admin.productPriceEvolution');
            Route::post('/importationxl', [ProductController::class, 'importationxl'])->name('admin.product.importationxl');
            Route::get('/importation', [ProductController::class, 'importation'])->name('admin.product.importation');
            Route::post('/merge', [ProductController::class, 'merge'])->name('admin.product.merge');
            Route::get('/getAttributeValue', [ProductController::class, 'getAttributeValue'])->name('admin.product.getAttributeValue');
            Route::post('/mergeing', [ProductController::class, 'mergeing'])->name('admin.product.mergeing');
            Route::post('/multipledelete', [ProductController::class, 'multipleDelete'])->name('admin.product.multipledelete')->middleware(['can:Supprimer article']);
        });

        //Provider routes
        Route::group([
            'prefix' => 'provider',
        ], function () {
            Route::get('/list', [ProviderController::class, 'index'])->name('admin.provider.index')->middleware(['can:Liste fournisseur']);
            Route::get('/create', [ProviderController::class, 'create'])->name('admin.provider.create')->middleware(['can:Ajouter fournisseur']);
            Route::post('/store', [ProviderController::class, 'store'])->name('admin.provider.store')->middleware(['can:Ajouter fournisseur']);
            Route::get('/{provider}/edit', [ProviderController::class, 'edit'])->name('admin.provider.edit')->middleware(['can:Modifier fournisseur']);
            Route::put('/{provider}/update', [ProviderController::class, 'update'])->name('admin.provider.update')->middleware(['can:Modifier fournisseur']);
            Route::get('/{provider}/delete', [ProviderController::class, 'delete'])->name('admin.provider.delete')->middleware(['can:Supprimer fournisseur']);
        });

        //Notification routes
        Route::group([
            'prefix' => 'notification',
        ], function () {
            Route::get('', [NotificationController::class, 'index'])->name('admin.notification.index');
            Route::get('/user/{user}/markallasread', [NotificationController::class, 'markAllAsRead'])->name('admin.notification.markallasread');
            Route::get('/user/{user}/markordersasread', [NotificationController::class, 'markOrdersAsRead'])->name('admin.notification.order.markallasread');
        });

        //Setting routes
        Route::group([
            'prefix' => 'setting',
        ], function () {
            Route::get('', [SettingController::class, 'index'])->name('admin.setting.index');
            Route::put('/update', [SettingController::class, 'updateSettings'])->name('admin.setting.update');

app/Models/Client.php
<?php

namespace App\Models;

use App\Notifications\ShopPasswordReset;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class Client  extends Authenticatable
{
    use HasFactory, SoftDeletes;
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'site',
        'password',
        'client_code',
        'email',
        'adresse',
        'mf',
        'rib',
        'phone',
        'phone2',
        'price',
        'discount',
        'google_id',
        'state',
        'city',
    ];

    protected $guard = 'shop';

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $appends = [
        'default_image_url'
    ];
    public function getImageUrlAttribute()
    {
        $image = $this->image;
        if ($image) {
            return $image->url;
        }
        return config('stock.image.default.provider');
    }
    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }

    public function pricings()
    {
        return $this->hasMany(ClientPricing::class);
    }

    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ShopPasswordReset($token));
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;
use Illuminate\Routing\Controller;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateProfileRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Spatie\Permission\Models\Role;
use Yajra\DataTables\Facades\DataTables;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $users = User::all();
        return view('admin.user.index', compact('users'));
    }

    public function create()
    {
        return view('admin.user.create');
    }

    public function store(CreateUserRequest $request)
    {
        try {
            DB::beginTransaction();
            $data = $request->all();
            $data['password'] = bcrypt('password');
            $user = User::create($data);
            $role = Role::find($data['role']);
            $user->assignRole($role);
            if ($request->file('avatar')) {
                $path = $this->addAttachment($request->file('avatar'));
                $user->image()->create(['url' => $path]);
            }
            DB::commit();
            return redirect()->route('admin.user.index')->with('success', "Ajouté avec succès!");
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error("File: " . $e->getFile() . " \nLine: " . $e->getLine() . " Error: " . $e->getMessage());
            return ($e->getMessage());
        }
    }

    public function edit(User $user)
    {
        return view('admin.user.edit', compact('user'));
    }

    public function update(UpdateUserRequest $request, User $user)
    {
        try {
            $data = $request->all();
            if ($request->file('avatar')) {
                if ($user->image()->exists()) {
                    $this->deleteAttachment($user->image->url);
                    $user->image()->delete();
                }
                $path = $this->addAttachment($request->file('avatar'));
                $user->image()->create(['url' => $path]);
            }

            $role = Role::find($data['role']);
            $user->syncRoles([$role]);

            $user->update($data);
            return redirect()->route('admin.user.index')->with('success', "Ajouté avec succès!");
        } catch (\Exception $e) {
            Log::error("File: " . $e->getFile() . " \nLine: " . $e->getLine() . " Error: " . $e->getMessage());
        }
    }

    public function delete(User $User)
    {
        try {
            $User->delete();
            return redirect()->route('admin.user.index')->with('success', "Supprimé avec succès!");
        } catch (\Exception $e) {
            Log::error("File: " . $e->getFile() . " \nLine: " . $e->getLine() . " Error: " . $e->getMessage());
        }
    }

    public function addAttachment($file)
    {
        $filePath = 'uploads/users/images/';
        $filename = $file->getClientOriginalName();
        $extension = $file->getClientOriginalExtension();
        $newFilename = $filename . '-' . uniqid();
        $fullPath = $filePath . $newFilename . '.' . $extension;

        if ($file->storeAs($filePath, $newFilename . '.' . $extension, 'public')) {
            $path = Storage::url($fullPath);
        }

        return $path;
    }

    public function deleteAttachment($path)
    {
        if (isset($path)) {
            if ($path != '') {
                $fileuri = str_replace('/storage', '', $path);
                Storage::disk('public')->delete($fileuri);
            }
        }
    }

    public function profile()
    {
        return view('admin.profile');
    }

    public function updateProfile(UpdateProfileRequest $request)
    {
        try {
            $user = User::find(auth()->user()->id);
            $data = $request->all();
            if ($request->file('avatar')) {
                if ($user->image()->exists()) {
                    $this->deleteAttachment($user->image->url);
                    $user->image()->delete();
                }
                $path = $this->addAttachment($request->file('avatar'));
                $user->image()->create(['url' => $path]);
            }
            if (isset($data['password']) && !empty($data['password'])) {
                $data['password'] = bcrypt($data['password']);
            }else{
                unset($data['password']);
            }
            $user->update($data);
            return redirect()->back()->with('success', "Modifié avec succès!");
        } catch (\Exception $e) {
            Log::error($e->getMessage());
        }
    }
}

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Liste des users')

@section('stylesheets')
    <link href="{{ url('assets/admin/plugins/datatable/css/dataTables.bootstrap5.min.css') }} " rel="stylesheet">
@endsection
@section('content')
    <!--start content-->
    <main class="page-content">
        <!--breadcrumb-->
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">{{config('stock.info.name')}} </div>
            <div class="ps-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item"><a href="{{ route('admin.home') }}"><i class="bx bx-home-alt"></i></a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page"> Liste des utilisateurs</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!--end breadcrumb-->

        <div class="card">
            <div class="card-header py-3">
                <div class="d-sm-flex align-items-center">
                    <h5 class="mb-2 mb-sm-0">Liste des utilisateurs</h5>
                    @canany(['Ajouter utilisateur'])
                        <div class="ms-auto">
                            <a class="btn btn-primary" href="{{ route('admin.user.create') }}"><i class="fa fa-plus"
                                    aria-hidden="true" title="Ajouter"></i>Ajouter un utilisateur</a>
                        </div>
                    @endcanany
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive mt-3">
                    <table id="example" class="table align-middle">
                        <thead class="table-secondary ">
                            <tr>

                                <th>#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Date de création</th>
                                <th>Rôle</th>
                                <th class="not-export-col">Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>
                                        <div class="d-flex align-items-center gap-3 cursor-pointer">
                                            <img src="{{ $user->image_url }}" class="rounded-circle" width="44"
                                                height="44" alt="">
                                            <div class="">
                                                <p class="mb-0">{{ $user->name }}</p>
                                            </div>
                                        </div>
                                    </td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->created_at->format('d/m/Y') }}</td>
                                    <td>{{ $user->role }}</td>
                                    <td>
                                        <div class="table-actions d-flex align-items-center gap-3 fs-6">
                                            {{-- <a href="javascript:;" class="text-primary" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Views"><i class="bi bi-eye-fill"></i></a> --}}

                                            @canany(['Modifier utilisateur'])
                                                <a href="{{ route('admin.user.edit', $user->id) }}" class="text-warning"
                                                    data-bs-toggle="tooltip" data-bs-placement="bottom" title="Edit"><i
                                                        class="bi bi-pencil-fill"></i></a>
                                            @endcanany
                                            @canany(['Supprimer utilisateur'])
                                            <form method="POST" action="{{ route('admin.user.delete', $user->id) }}">
                                                    {{ csrf_field() }}
                                                    <input name="_method" type="hidden" value="GET">
                                                    <a href="javascript:;" id="show_confirm" type="submit" class="text-danger show_confirm" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Supprimer" aria-label="Supprimer"><i class="bi bi-trash-fill"></i></a>

                                                    {{-- <button id="show_confirm" type="submit"
                                                        class="btn text-danger show_confirm" data-toggle="tooltip"
                                                        title="Supprimer"><i class="bi bi-trash-fill"></i></button> --}}
                                                </form>  
                                            @endcanany
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        </div>

    </main>
    <!--end page main-->
@endsection
@section('scripts')
    <script type="text/javascript" src="{{ asset('assets/admin/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/admin/plugins/datatable/js/dataTables.bootstrap5.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/admin/js/table-datatable.js') }}"></script>
    <script src="{{asset('assets/admin/plugins/sweetalert2/js/sweetalert2.min.js')}}"></script>

    <script type="text/javascript">
        $(document).on('click', '#show_confirm', function(event) {
            event.preventDefault();
            var form = $(this).closest("form");
            var name = $(this).data("name");
            Swal.fire({
                title: 'Êtes-vous sûr?',
                text: "Vous ne pourrez pas revenir en arrière !",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Confirmer',
                cancelButtonText: 'Annuler',
            }).then((result) => {
                if (result.isConfirmed) {
                    form.submit();
                }
            });
        });
    </script> 
@endsection